package rpg2;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class administrador_principal extends javax.swing.JFrame {

    public administrador_principal() {
        initComponents();
        this.jTabbedPane1.setTitleAt(0, "Administrar kioskos");
        this.jTabbedPane1.setTitleAt(1, "Administrar Regiones");
        this.jTabbedPane1.setTitleAt(2, "Administrar Departamentos y Municipios");
        this.jTabbedPane1.setTitleAt(3, "Administrar Reportes");
        lblDatos.setVisible(false);
        lblcodigoDepa.setVisible(false);
        cbCodigoDepartamento.setVisible(false);
        lblCodigoMuni.setVisible(false);
        txtCodigoMunicipio.setVisible(false);
        lblNombreMuni.setVisible(false);
        txtNombreMunicipio.setVisible(false);
        btnMunicipio.setVisible(false);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        txtCodigo = new javax.swing.JTextField();
        txtNombreKiosko = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCodigoRegion = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel16 = new javax.swing.JLabel();
        cbCodigoDepartamento = new javax.swing.JComboBox<>();
        lblCodigoMuni = new javax.swing.JLabel();
        txtNombreMunicipio = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtCodigoMunicipio = new javax.swing.JTextField();
        txtNombreDepartamento = new javax.swing.JTextField();
        lblDatos = new javax.swing.JLabel();
        lblcodigoDepa = new javax.swing.JLabel();
        btnMunicipio = new javax.swing.JButton();
        cbCodigoRegionP3 = new javax.swing.JComboBox<>();
        txtCodigoDepartamento = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblNombreMuni = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblRegionesMasEnvios = new javax.swing.JLabel();
        lblTotPaquetesEnviados = new javax.swing.JLabel();
        lblIngresosTotales = new javax.swing.JLabel();
        lblUsuaiosMasEnvios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Administrador");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        panel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 175, 109, -1));

        txtNombreKiosko.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreKiosko.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(txtNombreKiosko, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 253, 219, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo ");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 141, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 218, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo Region");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 305, -1, -1));

        cbCodigoRegion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbCodigoRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "NT", "NO", "SO", "SOC", "NOC" }));
        cbCodigoRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCodigoRegionActionPerformed(evt);
            }
        });
        panel1.add(cbCodigoRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 342, 100, -1));

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setText("Ingresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 436, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Administrar Kioskos");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 175, -1));

        jTabbedPane1.addTab("tab4", panel1);
        panel1.getAccessibleContext().setAccessibleParent(panel1);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Administrar Regiones");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Regiones disponibles");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("(M) Metropolitana");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("(NT) Norte");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("(NO) Nororiente");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("(NOC) Noroccidente");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("(SO) Suroriente");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("(SOC) Suroccidente");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Precio Estandar");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Precio Especial");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Q68.50");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Q58.68");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Q38.68");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Q34.00");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Q44.50");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Q35.00");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Q32.48");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Q29.00");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Q40.00");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Q25.00");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Q45.55");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Q35.48");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel6))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8))))
                        .addGap(41, 41, 41)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10))
                        .addGap(40, 40, 40)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel15))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel27)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel28)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel25))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel18))
                        .addGap(26, 26, 26)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17))
                        .addGap(28, 28, 28)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19))
                        .addGap(26, 26, 26)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel20))
                        .addGap(28, 28, 28)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel21))
                        .addGap(28, 28, 28)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", panel2);
        panel2.getAccessibleContext().setAccessibleParent(panel2);

        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Administrar Departamentos y Municipios");
        panel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        cbCodigoDepartamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbCodigoDepartamento.setForeground(new java.awt.Color(255, 102, 102));
        panel3.add(cbCodigoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 150, -1));

        lblCodigoMuni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCodigoMuni.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigoMuni.setText("Codigo de Municipio");
        panel3.add(lblCodigoMuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        txtNombreMunicipio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        panel3.add(txtNombreMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 90, -1));

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Ingresar Datos de Departamento");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        txtCodigoMunicipio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigoMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        panel3.add(txtCodigoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, -1));

        txtNombreDepartamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        panel3.add(txtNombreDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, -1));

        lblDatos.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        lblDatos.setForeground(new java.awt.Color(0, 0, 0));
        lblDatos.setText("Datos de Municipio");
        panel3.add(lblDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        lblcodigoDepa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblcodigoDepa.setForeground(new java.awt.Color(0, 0, 0));
        lblcodigoDepa.setText("Codigo Departamento");
        panel3.add(lblcodigoDepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        btnMunicipio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        btnMunicipio.setText("Ingresar Datos de Municipio");
        btnMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipioActionPerformed(evt);
            }
        });
        panel3.add(btnMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 240, -1));

        cbCodigoRegionP3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbCodigoRegionP3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "NT", "NO", "SO", "SOC", "NOC" }));
        cbCodigoRegionP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCodigoRegionP3ActionPerformed(evt);
            }
        });
        panel3.add(cbCodigoRegionP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 30));

        txtCodigoDepartamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigoDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        panel3.add(txtCodigoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Nombre Departamento");
        panel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Datos de Departamento");
        panel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Codigo Departamento");
        panel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        lblNombreMuni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombreMuni.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreMuni.setText("Nombre de Municipio");
        panel3.add(lblNombreMuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Codigo de Region");
        panel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jTabbedPane1.addTab("tab3", panel3);
        panel3.getAccessibleContext().setAccessibleParent(panel3);

        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Administrar Reportes");
        panel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Regiones con mas envios: ");
        panel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("No. total de paquetes enviados: ");
        panel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Ingresos totales: ");
        panel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Usuarios con mas paquetes enviados: ");
        panel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lblRegionesMasEnvios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRegionesMasEnvios.setForeground(new java.awt.Color(0, 0, 204));
        lblRegionesMasEnvios.setText("--");
        panel4.add(lblRegionesMasEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        lblTotPaquetesEnviados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTotPaquetesEnviados.setForeground(new java.awt.Color(0, 0, 204));
        lblTotPaquetesEnviados.setText("--");
        panel4.add(lblTotPaquetesEnviados, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        lblIngresosTotales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblIngresosTotales.setForeground(new java.awt.Color(0, 0, 204));
        lblIngresosTotales.setText("--");
        panel4.add(lblIngresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        lblUsuaiosMasEnvios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsuaiosMasEnvios.setForeground(new java.awt.Color(0, 0, 204));
        lblUsuaiosMasEnvios.setText("--");
        panel4.add(lblUsuaiosMasEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jTabbedPane1.addTab("tab2", panel4);
        panel4.getAccessibleContext().setAccessibleParent(panel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 58, 790, 500));
        jTabbedPane1.getAccessibleContext().setAccessibleName("AdAdministrar Reportes");

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Kioskos[] kiosko;
    Inicio_sesion is;
    Admin_Departamentos[] depa;
    Admin_Municipios[] muni;

    public void cargarClase(Inicio_sesion is, Kioskos[] kiosko, Admin_Departamentos[] depa, Admin_Municipios[] muni) {
        this.is = is;
        this.kiosko = kiosko;
        this.depa = depa;
        this.muni = muni;
    }
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.setVisible(false);
        is.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (txtCodigoDepartamento.getText().equals("") || txtNombreDepartamento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay algun dato que no ha sido ingresado");
        } else {
            boolean depaIngresado = false;
            for (int i = 0; i < depa.length; i++) {
                if (depa[i] != null) {
                    if (depa[i].getNombreDepartamento().equals(txtNombreDepartamento.getText()) || depa[i].getCodigoDepartamento().equals(txtCodigoDepartamento.getText())) {
                        JOptionPane.showMessageDialog(null, "Error, ya hay un departamento con los mismos datos");
                        depaIngresado = true;
                        break;
                    }
                }
            }

            if (!depaIngresado) {
                Admin_Departamentos dp = new Admin_Departamentos();

                dp.setCodigoDepartamento(txtCodigoDepartamento.getText());
                dp.setNombreDepartamento(txtNombreDepartamento.getText());
                dp.setCodigoRegion(cbCodigoRegionP3.getSelectedItem().toString());

                for (int i = 0; i < depa.length; i++) {
                    if (depa[i] == null) {
                        JOptionPane.showMessageDialog(null, "Departamento registrado con exito");
                        depa[i] = dp;
                        break;
                    }
                }
                lblDatos.setVisible(true);
                lblcodigoDepa.setVisible(true);
                cbCodigoDepartamento.setVisible(true);
                lblCodigoMuni.setVisible(true);
                txtCodigoMunicipio.setVisible(true);
                lblNombreMuni.setVisible(true);
                txtNombreMunicipio.setVisible(true);
                btnMunicipio.setVisible(true);
            }
            cbCodigoDepartamento.removeAllItems();
            for (int i = 0; i < depa.length; i++) {
                if (depa[i] != null) {
                    cbCodigoDepartamento.addItem(depa[i].getCodigoDepartamento());
                }
            }
            is.actualizarDepartamento(depa);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbCodigoRegionP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCodigoRegionP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigoRegionP3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txtCodigo.getText().equals("") || txtNombreKiosko.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay algun dato que no ha sido ingresado");
        } else {
            boolean ingresado = false;
            for (int i = 0; i < kiosko.length; i++) {
                if (kiosko[i] != null) {
                    if (kiosko[i].getCodigoKiosko().equals(txtCodigo.getText()) || kiosko[i].getNombre().equals(txtNombreKiosko.getText())) {
                        JOptionPane.showMessageDialog(null, "Error, ya hay un kiosko con los mismos datos");
                        ingresado = true;
                        break;
                    }
                }
            }

            if (!ingresado) {
                Kioskos kio = new Kioskos();

                kio.setCodigoKiosko(txtCodigo.getText());
                kio.setNombre(txtNombreKiosko.getText());
                kio.setCodigoRegion(cbCodigoRegion.getSelectedItem().toString());

                for (int i = 0; i < kiosko.length; i++) {
                    if (kiosko[i] == null) {
                        JOptionPane.showMessageDialog(null, "Kiosko registrado con exito");
                        kiosko[i] = kio;
                        break;
                    }
                }
                is.actualizarKiosko(kiosko);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbCodigoRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCodigoRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigoRegionActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipioActionPerformed
        if (txtCodigoMunicipio.getText().equals("") || txtNombreMunicipio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay algun dato que no ha sido ingresado");
        } else {
            boolean muniIngresado = false;
            for (int i = 0; i < muni.length; i++) {
                if (muni[i] != null) {
                    if (muni[i].getCodigoMunicipio().equals(txtCodigoMunicipio.getText()) || muni[i].getNombreMunicipio().equals(txtNombreMunicipio.getText())) {
                        JOptionPane.showMessageDialog(null, "Error, ya hay un municipio con los mismos datos");
                        muniIngresado = true;
                        break;
                    }
                }
            }

            if (!muniIngresado) {
                Admin_Municipios mn = new Admin_Municipios();

                mn.setCodigoMunicipio(txtCodigoMunicipio.getText());
                mn.setCodigoDepartamento(cbCodigoDepartamento.getSelectedItem().toString());
                mn.setNombreMunicipio(txtNombreMunicipio.getText());

                for (int i = 0; i < muni.length; i++) {
                    if (muni[i] == null) {
                        JOptionPane.showMessageDialog(null, "Municipio registrado con exito");
                        muni[i] = mn;
                        break;
                    }
                }
                is.actualizarMunicipios(muni);
            }
        }
    }//GEN-LAST:event_btnMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrador_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrador_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrador_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrador_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrador_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMunicipio;
    private javax.swing.JComboBox<String> cbCodigoDepartamento;
    private javax.swing.JComboBox<String> cbCodigoRegion;
    private javax.swing.JComboBox<String> cbCodigoRegionP3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoMuni;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblIngresosTotales;
    private javax.swing.JLabel lblNombreMuni;
    private javax.swing.JLabel lblRegionesMasEnvios;
    private javax.swing.JLabel lblTotPaquetesEnviados;
    private javax.swing.JLabel lblUsuaiosMasEnvios;
    private javax.swing.JLabel lblcodigoDepa;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoDepartamento;
    private javax.swing.JTextField txtCodigoMunicipio;
    private javax.swing.JTextField txtNombreDepartamento;
    private javax.swing.JTextField txtNombreKiosko;
    private javax.swing.JTextField txtNombreMunicipio;
    // End of variables declaration//GEN-END:variables
}
