package rpg2;

import javax.swing.JOptionPane;

/**
 *
 * @author bryan
 */
public class Inicio_sesion extends javax.swing.JFrame {

    Registro rg = new Registro();
    Principal pc = new Principal();
    administrador_principal admin = new administrador_principal();

    usuario usr[] = new usuario[10];
    Kioskos kiosko[] = new Kioskos[10];
    Admin_Departamentos depa[] = new Admin_Departamentos[10];
    Admin_Municipios muni[] = new Admin_Municipios[10];
    Tarjetas_debito tar[] = new Tarjetas_debito[10];
    Datos_facturacion fac[] = new Datos_facturacion[10];

    public void actualizarUsuario(usuario usr[]) {
        this.usr = usr;
    }

    public void actualizarKiosko(Kioskos kiosko[]) {
        this.kiosko = kiosko;
    }

    public void actualizarDepartamento(Admin_Departamentos depa[]) {
        this.depa = depa;
    }

    public void actualizarMunicipios(Admin_Municipios muni[]) {
        this.muni = muni;
    }

    public void actualizarTarjetas(Tarjetas_debito tar[]) {
        this.tar = tar;
    }

    public void actualizarDatosFacturacion(Datos_facturacion fac[]) {
        this.fac = fac;
    }

    public Inicio_sesion() {
        initComponents();
        rg.cargarClase(this, usr, kiosko);
        pc.cargarClase(this, tar, fac, depa, muni);
        admin.cargarClase(this, kiosko, depa, muni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        scrollbar1 = new java.awt.Scrollbar();
        button1 = new java.awt.Button();
        txtCorreoIni = new java.awt.TextField();
        txtContraIni = new java.awt.TextField();
        lblUsuario = new java.awt.Label();
        lblContraseña = new java.awt.Label();
        btnInicioSesion = new java.awt.Button();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setActionCommand("Ingresar");
        button1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        button1.setLabel("Registrarse");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        txtCorreoIni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtContraIni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsuario.setText("Correo Electronico");

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblContraseña.setText("Contraseña");

        btnInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicioSesion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnInicioSesion.setLabel("Inicias Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(txtContraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(txtCorreoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        //El codigo para ir a otra pestaña
        //necesito que esta interfaz deje de mostrarse.
        //luego que la interfaz registro se muestre
        this.setVisible(false);
        rg.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        if (txtCorreoIni.getText().equals("") || txtContraIni.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error, usuario o correo vacios");
        } else {

            boolean existe = false;
            boolean existeAdmin = false;
            for (int i = 0; i < usr.length; i++) {
                if (usr[i] != null) {
                    if (usr[i].getCorreo().equals(txtCorreoIni.getText()) && usr[i].getContraseña().equals(txtContraIni.getText())) {
                        existe = true;
                        pc.setUsr(usr[i]);

                        break;
                    }
                }
            }

            if (txtCorreoIni.getText().equals("ipc1_202108307@ipc1delivery.com") && txtContraIni.getText().equals("202108307")) {
                existeAdmin = true;
            }
            if (existe) {
                this.setVisible(false);
                pc.setVisible(true);
                txtCorreoIni.setText("");
                txtContraIni.setText("");

            } else if (existeAdmin) {
                this.setVisible(false);
                admin.setVisible(true);
            } else {

                JOptionPane.showMessageDialog(null, "Usuario o correo incorrecta");
            }
        }


    }//GEN-LAST:event_btnInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnInicioSesion;
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label lblContraseña;
    private java.awt.Label lblUsuario;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.TextField txtContraIni;
    private java.awt.TextField txtCorreoIni;
    // End of variables declaration//GEN-END:variables
}
